import {
  Home,
  Link as LinkIcon,
  BookOpen,
  FileText,
  Heart,
  Share2,
  Bookmark,
  Plus,
  UserCircle,
  Settings,
  LogOut,
  LogIn,
  Mail,
  Lock,
  Eye,
  EyeOff,
  AlertCircle,
  CheckCircle,
  X,
  ChevronRight,
  ChevronDown,
  Search,
  Menu,
  Image as ImageIcon,
  RefreshCw,
  LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  home: Home,
  rcmd: Heart,
  link: LinkIcon,
  collection: BookOpen,
  page: FileText,
  heart: Heart,
  share: Share2,
  bookmark: Bookmark,
  plus: Plus,
  user: UserCircle,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  email: Mail,
  password: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  alert: AlertCircle,
  success: CheckCircle,
  close: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  search: Search,
  menu: Menu,
  image: ImageIcon,
  spinner: RefreshCw,
};
